version: '3'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=SMSLog
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
        - mongo
    ports:
      - "8080:8081"   
  api: 
    build: ./API
    restart: always
    ports:
      - "3030:3000"
    environment:
      PORT: 3000
      MONGO_CONN_STRING: mongodb://mongo:27017/SMSLog
    depends_on:
      - mongo      
    links:
      - mongo             
